[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  publish = "build"


[build.environment]
 CI = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  