export const EMPLOYEE_CHECKLIST_ACTIONS = {
  ATTEMPT_TO_FETCH_EMPLOYEE_CHECKLIST: 'dashboard/@HOSPICE/ATTEMPT_TO_FETCH_EMPLOYEE_CHECKLIST',
  SET_FETCH_EMPLOYEE_CHECKLIST_SUCCEED: 'dashboard/@HOSPICE/SET_FETCH_EMPLOYEE_CHECKLIST_SUCCEED',
  SET_FETCH_EMPLOYEE_CHECKLIST_FAILURE: 'dashboard/@HOSPICE/SET_FETCH_EMPLOYEE_CHECKLIST_FAILURE',
  RESET_FETCH_EMPLOYEE_CHECKLIST_STATE: 'dashboard/@HOSPICE/RESET_FETCH_EMPLOYEE_CHECKLIST_STATE',

  ATTEMPT_TO_CREATE_EMPLOYEE_CHECKLIST: 'dashboard/@HOSPICE/ATTEMPT_TO_CREATE_EMPLOYEE_CHECKLIST',
  SET_CREATE_EMPLOYEE_CHECKLIST_SUCCEED: 'dashboard/@HOSPICE/SET_CREATE_EMPLOYEE_CHECKLIST_SUCCEED',
  SET_CREATE_EMPLOYEE_CHECKLIST_FAILURE: 'dashboard/@HOSPICE/SET_CREATE_EMPLOYEE_CHECKLIST_FAILURE',
  RESET_CREATE_EMPLOYEE_CHECKLIST_STATE: 'dashboard/@HOSPICE/RESET_CREATE_EMPLOYEE_CHECKLIST_STATE',

  ATTEMPT_TO_UPDATE_EMPLOYEE_CHECKLIST: 'dashboard/@HOSPICE/ATTEMPT_TO_UPDATE_EMPLOYEE_CHECKLIST',
  SET_UPDATE_EMPLOYEE_CHECKLIST_SUCCEED: 'dashboard/@HOSPICE/SET_UPDATE_EMPLOYEE_CHECKLIST_SUCCEED',
  SET_UPDATE_EMPLOYEE_CHECKLIST_FAILURE: 'dashboard/@HOSPICE/SET_UPDATE_EMPLOYEE_CHECKLIST_FAILURE',
  RESET_UPDATE_EMPLOYEE_CHECKLIST_STATE: 'dashboard/@HOSPICE/RESET_UPDATE_EMPLOYEE_CHECKLIST_STATE',

  ATTEMPT_TO_DELETE_EMPLOYEE_CHECKLIST: 'dashboard/@HOSPICE/ATTEMPT_TO_DELETE_EMPLOYEE_CHECKLIST',
  SET_DELETE_EMPLOYEE_CHECKLIST_SUCCEED: 'dashboard/@HOSPICE/SET_DELETE_EMPLOYEE_CHECKLIST_SUCCEED',
  SET_DELETE_EMPLOYEE_CHECKLIST_FAILURE: 'dashboard/@HOSPICE/SET_DELETE_EMPLOYEE_CHECKLIST_FAILURE',
  RESET_DELETE_EMPLOYEE_CHECKLIST_STATE: 'dashboard/@HOSPICE/RESET_DELETE_EMPLOYEE_CHECKLIST_STATE'
};

// FETCH EMPLOYEE CHECKLIST
export const attemptToFetchEmployeeChecklist = (data: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.ATTEMPT_TO_FETCH_EMPLOYEE_CHECKLIST,
  payload: data
});

export const setFetchEmployeeChecklistSucceed = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_FETCH_EMPLOYEE_CHECKLIST_SUCCEED,
  payload
});

export const setFetchEmployeeChecklistFailure = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_FETCH_EMPLOYEE_CHECKLIST_FAILURE,
  payload
});

export const resetFetchEmployeeChecklistState = (): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.RESET_FETCH_EMPLOYEE_CHECKLIST_STATE
});

// CREATE EMPLOYEE CHECKLIST
export const attemptToCreateEmployeeChecklist = (data: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.ATTEMPT_TO_CREATE_EMPLOYEE_CHECKLIST,
  payload: data
});

export const setCreateEmployeeChecklistSucceed = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_CREATE_EMPLOYEE_CHECKLIST_SUCCEED,
  payload
});

export const setCreateEmployeeChecklistFailure = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_CREATE_EMPLOYEE_CHECKLIST_FAILURE,
  payload
});

export const resetCreateEmployeeChecklistState = (): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.RESET_CREATE_EMPLOYEE_CHECKLIST_STATE
});

// UPDATE EMPLOYEE CHECKLIST
export const attemptToUpdateEmployeeChecklist = (data: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.ATTEMPT_TO_UPDATE_EMPLOYEE_CHECKLIST,
  payload: data
});

export const setUpdateEmployeeChecklistSucceed = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_UPDATE_EMPLOYEE_CHECKLIST_SUCCEED,
  payload
});

export const setUpdateEmployeeChecklistFailure = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_UPDATE_EMPLOYEE_CHECKLIST_FAILURE,
  payload
});

export const resetUpdateEmployeeChecklistState = (): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.RESET_UPDATE_EMPLOYEE_CHECKLIST_STATE
});

// DELETE EMPLOYEE CHECKLIST
export const attemptToDeleteEmployeeChecklist = (data: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.ATTEMPT_TO_DELETE_EMPLOYEE_CHECKLIST,
  payload: data
});

export const setDeleteEmployeeChecklistSucceed = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_DELETE_EMPLOYEE_CHECKLIST_SUCCEED,
  payload
});

export const setDeleteEmployeeChecklistFailure = (payload: Object): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.SET_DELETE_EMPLOYEE_CHECKLIST_FAILURE,
  payload
});

export const resetDeleteEmployeeChecklistState = (): BaseAction => ({
  type: EMPLOYEE_CHECKLIST_ACTIONS.RESET_DELETE_EMPLOYEE_CHECKLIST_STATE
});
