// @flow
export const PATIENT_CHECKLIST_ACTIONS = {
  ATTEMPT_TO_FETCH_PATIENT_CHECKLIST: "ATTEMPT_TO_FETCH_PATIENT_CHECKLIST",
  FETCH_PATIENT_CHECKLIST_SUCCEED: "FETCH_PATIENT_CHECKLIST_SUCCEED",
  FETCH_PATIENT_CHECKLIST_FAILURE: "FETCH_PATIENT_CHECKLIST_FAILURE",
  RESET_FETCH_PATIENT_CHECKLIST_STATE: "RESET_FETCH_PATIENT_CHECKLIST_STATE",

  ATTEMPT_TO_CREATE_PATIENT_CHECKLIST: "ATTEMPT_TO_CREATE_PATIENT_CHECKLIST",
  CREATE_PATIENT_CHECKLIST_SUCCEED: "CREATE_PATIENT_CHECKLIST_SUCCEED",
  CREATE_PATIENT_CHECKLIST_FAILURE: "CREATE_PATIENT_CHECKLIST_FAILURE",
  RESET_CREATE_PATIENT_CHECKLIST_STATE: "RESET_CREATE_PATIENT_CHECKLIST_STATE",

  ATTEMPT_TO_UPDATE_PATIENT_CHECKLIST: "ATTEMPT_TO_UPDATE_PATIENT_CHECKLIST",
  UPDATE_PATIENT_CHECKLIST_SUCCEED: "UPDATE_PATIENT_CHECKLIST_SUCCEED",
  UPDATE_PATIENT_CHECKLIST_FAILURE: "UPDATE_PATIENT_CHECKLIST_FAILURE",
  RESET_UPDATE_PATIENT_CHECKLIST_STATE: "RESET_UPDATE_PATIENT_CHECKLIST_STATE",

  ATTEMPT_TO_DELETE_PATIENT_CHECKLIST: "ATTEMPT_TO_DELETE_PATIENT_CHECKLIST",
  DELETE_PATIENT_CHECKLIST_SUCCEED: "DELETE_PATIENT_CHECKLIST_SUCCEED",
  DELETE_PATIENT_CHECKLIST_FAILURE: "DELETE_PATIENT_CHECKLIST_FAILURE",
  RESET_DELETE_PATIENT_CHECKLIST_STATE: "RESET_DELETE_PATIENT_CHECKLIST_STATE",
};

export const attemptToFetchPatientChecklist = (payload: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.ATTEMPT_TO_FETCH_PATIENT_CHECKLIST,
  payload,
});

export const setFetchPatientChecklistSucceed = (list: Array<any>) => ({
  type: PATIENT_CHECKLIST_ACTIONS.FETCH_PATIENT_CHECKLIST_SUCCEED,
  list,
});

export const setFetchPatientChecklistFailure = (error: string) => ({
  type: PATIENT_CHECKLIST_ACTIONS.FETCH_PATIENT_CHECKLIST_FAILURE,
  error,
});

export const resetFetchPatientChecklistState = () => ({
  type: PATIENT_CHECKLIST_ACTIONS.RESET_FETCH_PATIENT_CHECKLIST_STATE,
});

export const attemptToCreatePatientChecklist = (payload: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.ATTEMPT_TO_CREATE_PATIENT_CHECKLIST,
  payload,
});

export const setCreatePatientChecklistSucceed = (item: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.CREATE_PATIENT_CHECKLIST_SUCCEED,
  item,
});

export const setCreatePatientChecklistFailure = (error: string) => ({
  type: PATIENT_CHECKLIST_ACTIONS.CREATE_PATIENT_CHECKLIST_FAILURE,
  error,
});

export const resetCreatePatientChecklistState = () => ({
  type: PATIENT_CHECKLIST_ACTIONS.RESET_CREATE_PATIENT_CHECKLIST_STATE,
});

export const attemptToUpdatePatientChecklist = (payload: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.ATTEMPT_TO_UPDATE_PATIENT_CHECKLIST,
  payload,
});

export const setUpdatePatientChecklistSucceed = (item: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.UPDATE_PATIENT_CHECKLIST_SUCCEED,
  item,
});

export const setUpdatePatientChecklistFailure = (error: string) => ({
  type: PATIENT_CHECKLIST_ACTIONS.UPDATE_PATIENT_CHECKLIST_FAILURE,
  error,
});

export const resetUpdatePatientChecklistState = () => ({
  type: PATIENT_CHECKLIST_ACTIONS.RESET_UPDATE_PATIENT_CHECKLIST_STATE,
});

export const attemptToDeletePatientChecklist = (payload: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.ATTEMPT_TO_DELETE_PATIENT_CHECKLIST,
  payload,
});

export const setDeletePatientChecklistSucceed = (item: any) => ({
  type: PATIENT_CHECKLIST_ACTIONS.DELETE_PATIENT_CHECKLIST_SUCCEED,
  item,
});

export const setDeletePatientChecklistFailure = (error: string) => ({
  type: PATIENT_CHECKLIST_ACTIONS.DELETE_PATIENT_CHECKLIST_FAILURE,
  error,
});

export const resetDeletePatientChecklistState = () => ({
  type: PATIENT_CHECKLIST_ACTIONS.RESET_DELETE_PATIENT_CHECKLIST_STATE,
});
