export const POTENTIAL_ADMISSION_ACTIONS = {
  ATTEMPT_TO_FETCH_POTENTIAL_ADMISSION: 'dashboard/@HOSPICE/ATTEMPT_TO_FETCH_POTENTIAL_ADMISSION',
  SET_FETCH_POTENTIAL_ADMISSION_SUCCEED: 'dashboard/@HOSPICE/SET_FETCH_POTENTIAL_ADMISSION_SUCCEED',
  SET_FETCH_POTENTIAL_ADMISSION_FAILURE: 'dashboard/@HOSPICE/SET_FETCH_POTENTIAL_ADMISSION_FAILURE',
  RESET_FETCH_POTENTIAL_ADMISSION_STATE: 'dashboard/@HOSPICE/RESET_FETCH_POTENTIAL_ADMISSION_STATE',

  ATTEMPT_TO_CREATE_POTENTIAL_ADMISSION: 'dashboard/@HOSPICE/ATTEMPT_TO_CREATE_POTENTIAL_ADMISSION',
  SET_CREATE_POTENTIAL_ADMISSION_SUCCEED: 'dashboard/@HOSPICE/SET_CREATE_POTENTIAL_ADMISSION_SUCCEED',
  SET_CREATE_POTENTIAL_ADMISSION_FAILURE: 'dashboard/@HOSPICE/SET_CREATE_POTENTIAL_ADMISSION_FAILURE',
  RESET_CREATE_POTENTIAL_ADMISSION_STATE: 'dashboard/@HOSPICE/RESET_CREATE_POTENTIAL_ADMISSION_STATE',

  ATTEMPT_TO_UPDATE_POTENTIAL_ADMISSION: 'dashboard/@HOSPICE/ATTEMPT_TO_UPDATE_POTENTIAL_ADMISSION',
  SET_UPDATE_POTENTIAL_ADMISSION_SUCCEED: 'dashboard/@HOSPICE/SET_UPDATE_POTENTIAL_ADMISSION_SUCCEED',
  SET_UPDATE_POTENTIAL_ADMISSION_FAILURE: 'dashboard/@HOSPICE/SET_UPDATE_POTENTIAL_ADMISSION_FAILURE',
  RESET_UPDATE_POTENTIAL_ADMISSION_STATE: 'dashboard/@HOSPICE/RESET_UPDATE_POTENTIAL_ADMISSION_STATE',

  ATTEMPT_TO_DELETE_POTENTIAL_ADMISSION: 'dashboard/@HOSPICE/ATTEMPT_TO_DELETE_POTENTIAL_ADMISSION',
  SET_DELETE_POTENTIAL_ADMISSION_SUCCEED: 'dashboard/@HOSPICE/SET_DELETE_POTENTIAL_ADMISSION_SUCCEED',
  SET_DELETE_POTENTIAL_ADMISSION_FAILURE: 'dashboard/@HOSPICE/SET_DELETE_POTENTIAL_ADMISSION_FAILURE',
  RESET_DELETE_POTENTIAL_ADMISSION_STATE: 'dashboard/@HOSPICE/RESET_DELETE_POTENTIAL_ADMISSION_STATE'
};

// Fetch Actions
export const attemptToFetchPotentialAdmission = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.ATTEMPT_TO_FETCH_POTENTIAL_ADMISSION,
  payload: data,
});

export const setFetchPotentialAdmissionSucceed = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_FETCH_POTENTIAL_ADMISSION_SUCCEED,
  payload: data,
});

export const setFetchPotentialAdmissionFailure = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_FETCH_POTENTIAL_ADMISSION_FAILURE,
  payload: data,
});

export const resetFetchPotentialAdmissionState = () => ({
  type: POTENTIAL_ADMISSION_ACTIONS.RESET_FETCH_POTENTIAL_ADMISSION_STATE,
});

// Create Actions
export const attemptToCreatePotentialAdmission = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.ATTEMPT_TO_CREATE_POTENTIAL_ADMISSION,
  payload: data,
});

export const setCreatePotentialAdmissionSucceed = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_CREATE_POTENTIAL_ADMISSION_SUCCEED,
  payload: data,
});

export const setCreatePotentialAdmissionFailure = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_CREATE_POTENTIAL_ADMISSION_FAILURE,
  payload: data,
});

export const resetCreatePotentialAdmissionState = () => ({
  type: POTENTIAL_ADMISSION_ACTIONS.RESET_CREATE_POTENTIAL_ADMISSION_STATE,
});

// Update Actions
export const attemptToUpdatePotentialAdmission = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.ATTEMPT_TO_UPDATE_POTENTIAL_ADMISSION,
  payload: data,
});

export const setUpdatePotentialAdmissionSucceed = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_UPDATE_POTENTIAL_ADMISSION_SUCCEED,
  payload: data,
});

export const setUpdatePotentialAdmissionFailure = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_UPDATE_POTENTIAL_ADMISSION_FAILURE,
  payload: data,
});

export const resetUpdatePotentialAdmissionState = () => ({
  type: POTENTIAL_ADMISSION_ACTIONS.RESET_UPDATE_POTENTIAL_ADMISSION_STATE,
});

// Delete Actions
export const attemptToDeletePotentialAdmission = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.ATTEMPT_TO_DELETE_POTENTIAL_ADMISSION,
  payload: data,
});

export const setDeletePotentialAdmissionSucceed = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_DELETE_POTENTIAL_ADMISSION_SUCCEED,
  payload: data,
});

export const setDeletePotentialAdmissionFailure = (data) => ({
  type: POTENTIAL_ADMISSION_ACTIONS.SET_DELETE_POTENTIAL_ADMISSION_FAILURE,
  payload: data,
});

export const resetDeletePotentialAdmissionState = () => ({
  type: POTENTIAL_ADMISSION_ACTIONS.RESET_DELETE_POTENTIAL_ADMISSION_STATE,
});
