export const CLIENT_SERVICES = [
  {
    code: "IV",
    name: "Initial Visit",
    isClientRequired: true,
    permission: [
      "Case Manager",
      "Registered Nurse",
      "MSW",
      "Director of Nurse",
      "LPN",
      "Medical Director",
      "Chaplain",
    ],
  },
  {
    code: "PRN",
    name: "PRN",
    isClientRequired: true,
    permission: [
      "Case Manager",
      "Registered Nurse",
      "Director of Nurse",
      "LPN",
      "Medical Director",
    ],
  },
  {
    code: "DC",
    name: "Discharge",
    isClientRequired: true,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "SUP",
    name: "Supervisory Visit",
    isClientRequired: true,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "IDT-PH",
    name: "IDT Meeting Via Phone",
    isClientRequired: false,
    permission: ["*"],
  },
  {
    code: "HUV",
    name: "HUV",
    isClientRequired: false,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "SFV",
    name: "SFV",
    isClientRequired: false,
    permission: [
      "Case Manager",
      "Registered Nurse",
      "Director of Nurse",
      "LPN",
    ],
  },
  {
    code: "IDT-PH",
    name: "IDT Meeting In Person",
    isClientRequired: false,
    permission: ["*"],
  },
  {
    code: "IDT-PH",
    name: "IDT Meeting Thru Notes",
    isClientRequired: false,
    permission: ["*"],
  },
  { code: "OC", name: "On-Call", isClientRequired: false, permission: ["*"] },
  {
    code: "RC",
    name: "Recertification Visit",
    isClientRequired: true,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "SM",
    name: "Staff Meeting",
    isClientRequired: false,
    permission: ["*"],
  },
  {
    code: "IN",
    name: "In-Service",
    isClientRequired: false,
    permission: ["*"],
  },
  {
    code: "EV",
    name: "Evaluation Visit",
    isClientRequired: true,
    permission: [
      "Case Manager",
      "Registered Nurse",
      "Director of Nurse",
      "Nurse Practioner",
    ],
  },
  {
    code: "SWV",
    name: "Social Worker Visit",
    isClientRequired: true,
    permission: ["MSW"],
  },

  {
    code: "RV",
    name: "Regular Visit",
    isClientRequired: true,
    permission: [
      "Certified Nurse Assistant",
      "Case Manager",
      "Registered Nurse",
      "MSW",
      "Director of Nurse",
      "LPN",
      "Medical Director",
      "Chaplain",
    ],
  },
  {
    code: "BV",
    name: "Bereavement Visit",
    isClientRequired: true,
    permission: ["Chaplain", "Bereavement"],
  },
  {
    code: "HV",
    name: "Home Health Aid Visit",
    isClientRequired: true,
    permission: ["Certified Nurse Assistant"],
  },
  {
    code: "F/UV",
    name: "Follow Up Visit",
    isClientRequired: true,
    permission: [
      "Case Manager",
      "MSW",
      "Director of Nurse",
      "Registered Nurse",
      "LPN",
      "Medical Director",
      "Chaplain",
    ],
  },
  {
    code: "O",
    name: "Orientation",
    isClientRequired: false,
    permission: ["*"],
  },
  {
    code: "VV",
    name: "Volunteer Visit",
    isClientRequired: true,
    permission: ["Volunteer"],
  },
  {
    code: "DPV",
    name: "Death pronouncement",
    isClientRequired: true,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "APV",
    name: "Admission Visit",
    isClientRequired: true,
    permission: ["Case Manager", "Registered Nurse", "Director of Nurse"],
  },
  {
    code: "ATD",
    name: "Attendance",
    isClientRequired: false,
    permission: [
      "Administrative Manager",
      "Case Manager",
      "Director of Nurse",
      "Registered Nurse",
      "Office Manager",
      "Administrator",
    ],
  },
  { code: "OTH", name: "Other", isClientRequired: false, permission: ["*"] },
];

export const SEARCH_KEYWORDS = [
  "ALL",
  "Order Number",
  "Item",
  "Description",
  "Vendor",
];
export const LOCAL_STORAGE_IDS = {
  user: "fsuser",
  headersArriveTable: "headers_arrive-table",
  viewProfile: "viewProfile",
  columnsHeaderProfile: "columnsHeaderProfile",
  usedLocation: "used-location",
  usedPerson: "used-person",
  reference: "reference",
  queryFilter: "queryFilter",
  cwRangeGap: "cwRangeGap",
  token: "fs_token",
  expirationDate: "expirationDate",
  userId: "userId",
  dExists: "d_exists",
};

export const DEFAULT_ITEM = { name: "", value: "", label: "" };
export const DATE_TYPE_SELECTION = [
  { name: "Today", value: "today", label: "Today", id: "1" },
  { name: "Yesterday", value: "yesterday", label: "Yesterday", id: "2" },
  { name: "Tomorrow", value: "tomorrow", label: "Tomorrow", id: "3" },
  { name: "Last Week", value: "lastWeek", label: "Last Week", id: "4" },
  { name: "This Week", value: "thisWeek", label: "This Week", id: "5" },
  { name: "Last Month", value: "lastMonth", label: "Last Month", id: "6" },
  { name: "This Month", value: "thisMonth", label: "This Month", id: "7" },
  { name: "Last 30 Days", value: "last30Days", label: "Last 30 Days", id: "9" },
  {
    name: "Last 90 Days",
    value: "last90Days",
    label: "Last 90 Days",
    id: "10",
  },
  { name: "YTD", value: "ytd", label: "YTD", id: "11" },
  { name: "Custom", value: "custom", label: "Custom", id: "12" },
];
export const ACTION_STATUSES = {
  PENDING: "Pending",
  SUCCEED: "Succeed",
  FAILED: "Failed",
  UNDEFINED: undefined,
};

export const INPUT_STATUSES = {
  VALID: "valid",
  INVALID: "invalid",
  UNDEFINED: undefined,
};

export const INPUT_CLASS_NAMES = {
  [INPUT_STATUSES.VALID]: "valid-input",
  [INPUT_STATUSES.INVALID]: "invalid-input",
};

export const DEFAULT_ERROR = {
  debug: "Something went wrong",
  details: "Something went wrong",
};

export const countries = [
  { name: "UNITED STATES", code: "US" },
  { name: "AFGHANISTAN", code: "AF" },
  { name: "Aland Islands", code: "AX" },
  { name: "ALBANIA", code: "AL" },
  { name: "ALGERIA", code: "DZ" },
  { name: "AMERICAN SAMOA", code: "AS" },
  { name: "ANDORRA", code: "AD" },
  { name: "ANGOLA", code: "AO" },
  { name: "ANGUILLA", code: "AI" },
  { name: "ANTARCTICA", code: "AQ" },
  { name: "ANTIGUA AND BARBUDA", code: "AG" },
  { name: "ARGENTINA", code: "AR" },
  { name: "ARMENIA", code: "AM" },
  { name: "ARUBA", code: "AW" },
  { name: "AUSTRALIA", code: "AU" },
  { name: "AUSTRIA", code: "AT" },
  { name: "AZERBAIJAN", code: "AZ" },
  { name: "BAHAMAS", code: "BS" },
  { name: "BAHRAIN", code: "BH" },
  { name: "BANGLADESH", code: "BD" },
  { name: "BARBADOS", code: "BB" },
  { name: "BELARUS", code: "BY" },
  { name: "BELGIUM", code: "BE" },
  { name: "BELIZE ", code: "BZ" },
  { name: "BENIN", code: "BJ" },
  { name: "BERMUDA", code: "BM" },
  { name: "BHUTAN", code: "BT" },
  { name: "BOLIVIA", code: "BO" },
  { name: "BOSNIA AND HERZEGOWINA", code: "BA" },
  { name: "BOTSWANA", code: "BW" },
  { name: "BOUVET ISLAND", code: "BV" },
  { name: "BRAZIL", code: "BR" },
  { name: "BRITISH INDIAN OCEAN TERRITORY", code: "IO" },
  { name: "BRUNEI DARUSSALAM", code: "BN" },
  { name: "BULGARIA", code: "BG" },
  { name: "BURKINA FASO", code: "BF" },
  { name: "BURUNDI", code: "BI" },
  { name: "CAMBODIA", code: "KH" },
  { name: "CAMEROON", code: "CM" },
  { name: "CANADA", code: "CA" },
  { name: "CAPE VERDE", code: "CV" },
  { name: "CAYMAN ISLANDS", code: "KY" },
  { name: "CENTRAL AFRICAN REPUBLIC", code: "CF" },
  { name: "CHAD", code: "TD" },
  { name: "CHILE", code: "CL" },
  { name: "CHINA", code: "CN" },
  { name: "CHRISTMAS ISLAND", code: "CX" },
  { name: "COCOS (KEELING) ISLANDS", code: "CC" },
  { name: "COLOMBIA", code: "CO" },
  { name: "COMOROS", code: "KM" },
  { name: "CONGO (Brazzaville)", code: "CG" },
  { name: "CONGO (Kinshasa)", code: "CD" },
  { name: "COOK ISLANDS", code: "CK" },
  { name: "COSTA RICA", code: "CR" },
  { name: "COTE D'IVOIRE'", code: "CI" },
  { name: "CROATIA (local name: Hrvatska)", code: "HR" },
  { name: "CUBA", code: "CU" },
  { name: "CYPRUS", code: "CY" },
  { name: "CZECH REPUBLIC", code: "CZ" },
  { name: "DENMARK", code: "DK" },
  { name: "DJIBOUTI", code: "DJ" },
  { name: "DOMINICA", code: "DM" },
  { name: "DOMINICAN REPUBLIC", code: "DO" },
  { name: "EAST TIMOR", code: "TP" },
  { name: "ECUADOR", code: "EC" },
  { name: "EGYPT", code: "EG" },
  { name: "EL SALVADOR", code: "SV" },
  { name: "EQUATORIAL GUINEA", code: "GQ" },
  { name: "ERITREA", code: "ER" },
  { name: "ESTONIA", code: "EE" },
  { name: "ETHIOPIA", code: "ET" },
  { name: "FALKLAND ISLANDS (MALVINAS)", code: "FK" },
  { name: "FAROE ISLANDS", code: "FO" },
  { name: "FIJI", code: "FJ" },
  { name: "FINLAND", code: "FI" },
  { name: "FRANCE", code: "FR" },
  { name: "FRANCE, METROPOLITAN", code: "FX" },
  { name: "FRENCH GUIANA", code: "GF" },
  { name: "FRENCH POLYNESIA", code: "PF" },
  { name: "FRENCH SOUTHERN TERRITORIES", code: "TF" },
  { name: "GABON", code: "GA" },
  { name: "GAMBIA", code: "GM" },
  { name: "GEORGIA", code: "GE" },
  { name: "GERMANY", code: "DE" },
  { name: "GHANA", code: "GH" },
  { name: "GIBRALTAR", code: "GI" },
  { name: "GREECE", code: "GR" },
  { name: "GREENLAND", code: "GL" },
  { name: "GRENADA", code: "GD" },
  { name: "GUADELOUPE", code: "GP" },
  { name: "GUAM", code: "GU" },
  { name: "GUATEMALA", code: "GT" },
  { name: "Guernsey, Bailiwick of", code: "GG" },
  { name: "GUINEA", code: "GN" },
  { name: "GUINEA-BISSAU", code: "GW" },
  { name: "GUYANA", code: "GY" },
  { name: "HAITI", code: "HT" },
  { name: "HEARD AND MC DONALD ISLANDS", code: "HM" },
  { name: "HOLY SEE (VATICAN CITY STATE)", code: "VA" },
  { name: "HONDURAS", code: "HN" },
  { name: "HONG KONG", code: "HK" },
  { name: "HUNGARY", code: "HU" },
  { name: "ICELAND", code: "IS" },
  { name: "INDIA", code: "IN" },
  { name: "INDONESIA", code: "ID" },
  { name: "IRAN (ISLAMIC REPUBLIC OF)", code: "IR" },
  { name: "IRAQ", code: "IQ" },
  { name: "IRELAND", code: "IE" },
  { name: "Isle of Man", code: "IM" },
  { name: "ISRAEL", code: "IL" },
  { name: "ITALY", code: "IT" },
  { name: "JAMAICA", code: "JM" },
  { name: "JAPAN", code: "JP" },
  { name: "Jersey, Bailiwick of", code: "JE" },
  { name: "JORDAN", code: "JO" },
  { name: "KAZAKHSTAN", code: "KZ" },
  { name: "KENYA", code: "KE" },
  { name: "KIRIBATI", code: "KI" },
  { name: "KOREA, D.P.R.O.", code: "KP" },
  { name: "KOREA, REPUBLIC OF (KR)", code: "KR" },
  { name: "KOREA, REPUBLIC OF (KO)", code: "KO" },
  { name: "KUWAIT", code: "KW" },
  { name: "KYRGYZSTAN", code: "KG" },
  { name: "LAOS", code: "LA" },
  { name: "LATVIA", code: "LV" },
  { name: "LEBANON", code: "LB" },
  { name: "LESOTHO", code: "LS" },
  { name: "LIBERIA", code: "LR" },
  { name: "LIBYAN ARAB JAMAHIRIYA", code: "LY" },
  { name: "LIECHTENSTEIN", code: "LI" },
  { name: "LITHUANIA", code: "LT" },
  { name: "LUXEMBOURG", code: "LU" },
  { name: "MACAU", code: "MO" },
  { name: "MACEDONIA", code: "MK" },
  { name: "MADAGASCAR", code: "MG" },
  { name: "MALAWI", code: "MW" },
  { name: "MALAYSIA", code: "MY" },
  { name: "MALDIVES", code: "MV" },
  { name: "MALI", code: "ML" },
  { name: "MALTA", code: "MT" },
  { name: "MARSHALL ISLANDS", code: "MH" },
  { name: "MARTINIQUE", code: "MQ" },
  { name: "MAURITANIA", code: "MR" },
  { name: "MAURITIUS", code: "MU" },
  { name: "MAYOTTE", code: "YT" },
  { name: "MEXICO", code: "MX" },
  { name: "MICRONESIA, FEDERATED STATES OF", code: "FM" },
  { name: "MOLDOVA, REPUBLIC OF", code: "MD" },
  { name: "MONACO", code: "MC" },
  { name: "MONGOLIA", code: "MN" },
  { name: "MONTSERRAT", code: "MS" },
  { name: "MOROCCO", code: "MA" },
  { name: "MOZAMBIQUE", code: "MZ" },
  { name: "MYANMAR (Burma)", code: "MM" },
  { name: "NAMIBIA", code: "NA" },
  { name: "NAURU", code: "NR" },
  { name: "NEPAL", code: "NP" },
  { name: "NETHERLANDS", code: "NL" },
  { name: "NETHERLANDS ANTILLES", code: "AN" },
  { name: "NEW CALEDONIA", code: "NC" },
  { name: "NEW ZEALAND", code: "NZ" },
  { name: "NICARAGUA", code: "NI" },
  { name: "NIGER", code: "NE" },
  { name: "NIGERIA", code: "NG" },
  { name: "NIUE", code: "NU" },
  { name: "NORFOLK ISLAND", code: "NF" },
  { name: "NORTHERN MARIANA ISLANDS", code: "MP" },
  { name: "NORWAY", code: "NO" },
  { name: "OMAN", code: "OM" },
  { name: "PAKISTAN", code: "PK" },
  { name: "PALAU", code: "PW" },
  { name: "Palestinian Territory, Occupied", code: "PS" },
  { name: "PANAMA", code: "PA" },
  { name: "PAPUA NEW GUINEA", code: "PG" },
  { name: "PARAGUAY", code: "PY" },
  { name: "PERU", code: "PE" },
  { name: "PHILIPPINES", code: "PH" },
  { name: "PITCAIRN", code: "PN" },
  { name: "POLAND", code: "PL" },
  { name: "PORTUGAL", code: "PT" },
  { name: "PUERTO RICO", code: "PR" },
  { name: "QATAR", code: "QA" },
  { name: "REUNION", code: "RE" },
  { name: "ROMANIA", code: "RO" },
  { name: "RUSSIAN FEDERATION", code: "RU" },
  { name: "RWANDA", code: "RW" },
  { name: "SAINT KITTS AND NEVIS", code: "KN" },
  { name: "SAINT LUCIA", code: "LC" },
  { name: "SAINT VINCENT AND THE GRENADINES", code: "VC" },
  { name: "SAIPAN", code: "SS" },
  { name: "SAMOA", code: "WS" },
  { name: "SAN MARINO", code: "SM" },
  { name: "SAO TOME AND PRINCIPE", code: "ST" },
  { name: "SAUDI ARABIA", code: "SA" },
  { name: "SENEGAL", code: "SN" },
  { name: "SERBIA", code: "RS" },
  { name: "Serbia and Montenegro", code: "CS" },
  { name: "SEYCHELLES", code: "SC" },
  { name: "SIERRA LEONE", code: "SL" },
  { name: "SINGAPORE", code: "SG" },
  { name: "SLOVAKIA (Slovak Republic)", code: "SK" },
  { name: "SLOVENIA", code: "SI" },
  { name: "SOLOMON ISLANDS", code: "SB" },
  { name: "SOMALIA", code: "SO" },
  { name: "SOUTH AFRICA", code: "ZA" },
  { name: "SOUTH GEORGIA AND SOUTH S.S.", code: "GS" },
  { name: "SPAIN", code: "ES" },
  { name: "SRI LANKA", code: "LK" },
  { name: "ST. HELENA", code: "SH" },
  { name: "ST. PIERRE AND MIQUELON", code: "PM" },
  { name: "SUDAN", code: "SD" },
  { name: "SURINAME", code: "SR" },
  { name: "SVALBARD AND JAN MAYEN ISLANDS", code: "SJ" },
  { name: "SWAZILAND", code: "SZ" },
  { name: "SWEDEN", code: "SE" },
  { name: "SWITZERLAND", code: "CH" },
  { name: "SYRIAN ARAB REPUBLIC", code: "SY" },
  { name: "TAIWAN", code: "TW" },
  { name: "TAJIKISTAN", code: "TJ" },
  { name: "TANZANIA, UNITED REPUBLIC OF", code: "TZ" },
  { name: "THAILAND", code: "TH" },
  { name: "Timor-Leste, Democratic Republic of", code: "TL" },
  { name: "TOGO", code: "TG" },
  { name: "TOKELAU", code: "TK" },
  { name: "TONGA", code: "TO" },
  { name: "TRINIDAD AND TOBAGO", code: "TT" },
  { name: "TUNISIA", code: "TN" },
  { name: "TURKEY", code: "TR" },
  { name: "TURKMENISTAN", code: "TM" },
  { name: "TURKS AND CAICOS ISLANDS", code: "TC" },
  { name: "TUVALU", code: "TV" },
  { name: "U.S. MINOR ISLANDS", code: "UM" },
  { name: "UGANDA", code: "UG" },
  { name: "UKRAINE", code: "UA" },
  { name: "UNITED ARAB EMIRATES", code: "AE" },
  { name: "UNITED KINGDOM", code: "GB" },
  { name: "URUGUAY", code: "UY" },
  { name: "UZBEKISTAN", code: "UZ" },
  { name: "VANUATU", code: "VU" },
  { name: "VENEZUELA", code: "VE" },
  { name: "VIET NAM", code: "VN" },
  { name: "VIRGIN ISLANDS (BRITISH)", code: "VG" },
  { name: "VIRGIN ISLANDS (U.S.)", code: "VI" },
  { name: "WALLIS AND FUTUNA ISLANDS", code: "WF" },
  { name: "WESTERN SAHARA", code: "EH" },
  { name: "YEMEN", code: "YE" },
  { name: "YUGOSLAVIA (Serbia and Montenegro)", code: "YU" },
  { name: "ZAMBIA", code: "ZM" },
  { name: "ZIMBABWE", code: "ZW" },
];
export const QUANTITY_UOM = [
  "Carton",
  "Box",
  "Case",
  "Pack",
  "Pcs",
  "Bag",
  "Fixed",
];
export const LIMIT_ITEM_PRINT = 15;
export const SUPPLY_VENDOR = [
  "Amazon",
  "Medline",
  "Dollar Tree",
  "Costco",
  "Sams",
  "Walmart",
  "Mckesson",
  "Walgreen",
  "99Only",
  "Walma",
];
export const SUPPLY_STATUS = [
  "Order",
  "Fulfill",
  "Picked Up",
  "Delivered",
  "Return",
];
export const SUPPLY_CATEGORY = [
  "Office",
  "DME",
  "Pharmacy",
  "Diabetic Shake",
  "Underpads",
  "Brief",
  "Immnue System",
  "Thermometer",
  "Bandages",
  "Gloves",
  "Hydration Drink",
  "Shampoo",
  "Jelly",
  "Food Thickener",
  "Ointment",
  "Pill Crusher and Grinder",
  "Wipes",
  "ToothPaste",
  "Basin",
  "Towel",
  "Swabs Sponge",
  "Drain Sponge",
  "Shave Cream",
  "Urinal",
  "Razor",
  "Clipper",
  "Cream",
  "Combs",
  "Kit",
  "Nutrition Shake",
  "Carbonless Paper",
  "Blood Oxygen Monitor",
  "Saline Solution for Inhalation",
  "Perineal Cleanser",
  "Sterile Lancets",
  "Glycerin Swabsticks",
  "Underwear/Pull-ups",
  "Other",
  "Lotion",
  "Cleanser",
  "Toothbrush",
  "Pill Crusher",
  "Sanitizer",
  "Lancet",
  "Facial Tissue",
  "Abdominal Pad",
  "Adhesive Pad",
  "Cotton",
  "Gauze",
  "Saline",
  "Lip Balm",
  "Dressing Pad",
  "Foam Dressing",
  "Syringe Sterile",
  "Steri-strip",
  "Surgical Tape",
  "Nasogastric Tube",
  "Silicone-Elastomer Latex",
  "Stamp",
  "Body Wash",
  "Band-Aid",
  "Powder Antifungal",
  "Masks",
  "Belt",
  "Pillow",
  "Gel",
  "Disposable Bag",
  "WashCloth",
  "Socks",
  "Wound Dressing",
  "Shoe",
  "Tongue Depressor",
  "Plastic",
  "Straw",
  "BP Monitor",
  "Soap",
  "Matress Pad",
  "Catheters",
  "Removal Kit",
  "Urine Drainage Bag",
  "Bed Pan",
  "Condom Catheter",
  "Injection",
  "Bed Alarm",
  "Covid-19 Test",
  "Flange",
  "Drainable Pouch",
  "Deodorant",
  "Hospital Gown",
  "Tax Fee",
  "Office Tax Fee",
  "Supply Tax Fee",
  "Services Tax Fee",
  "Office Shipping Fee",
  "Supply Shipping Fee",
  "Shipping Fee",
  "Powder",
  "Mouthwash",
  "Amazon Promotion Applied",
  "Seat Cushion",
  "Eye Drop",
  "Solution",
  "Shields",
  "PPE",
  "Disposable Boot & Shoe Covers",
  "Swabs",
  "Tablet Cutter",
  "Utilities",
  "Office Rent",
  "Payroll",
  "Marketing",
  "Services",
  "Transportation",
  "Wound Measuring",
];

export const SUPPLY_PAYMENT_METHOD = ["Cash", "Card", "Check", "Bank"];
export const DIVINE_PATIENT_LIST = ["Nargel Velasco", "Jasmin Velasco"];
export const HOSPICE_FACILITIES = ["Pacifica", "Summerlin"];
export const DIVINE_EMPLOYEES = [
  {
    name: "Jasmin Velasco",
    position: "Office Manager",
  },
  {
    name: "Nargel Velasco",
    position: "Information Technology",
  },
];

export const VENDOR_TYPE = [
  {
    id: "Transportation",
    category: "vendor",
    name: "Transportation",
    label: "Transportation",
    value: "Transportation",
  },
  { id: "DME", category: "vendor", name: "DME", label: "DME", value: "DME" },
  {
    id: "Supplies",
    category: "vendor",
    name: "Supplies",
    label: "Supplies",
    value: "Supplies",
  },
  {
    id: "Services",
    category: "vendor",
    name: "Services",
    label: "Services",
    value: "Services",
  },
  {
    id: "Food",
    category: "vendor",
    name: "Food",
    label: "Food",
    value: "Food",
  },
  {
    id: "Insurance",
    category: "vendor",
    name: "Insurance",
    label: "Insurance",
    value: "Insurance",
  },
  {
    id: "Bank",
    category: "vendor",
    name: "Bank",
    label: "Bank",
    value: "Bank",
  },
  {
    id: "Pharmacy",
    category: "vendor",
    name: "Pharmacy",
    label: "Pharmacy",
    value: "Pharmacy",
  },
];
export const LOCATION_TYPE = [
  {
    id: "Home",
    category: "location",
    name: "Home",
    label: "Home",
    value: "Home",
    code: "HM",
  },
  {
    id: "Group Home",
    category: "location",
    name: "Group Home",
    label: "Group Home",
    value: "Group Home",
    code: "GH",
  },
  {
    id: "Assisted Living",
    category: "location",
    name: "Assisted Living",
    label: "Assisted Living",
    value: "Assisted Living",
    code: "AL",
  },
];
export const EMPLOYEE_TYPE = [
  {
    id: "fullTime",
    category: "employee",
    name: "Full-Time",
    label: "Full-Time",
    value: "Full-Time",
    code: "Full-time",
  },
  {
    id: "partTime",
    category: "employee",
    name: "Part-time",
    label: "Part-time",
    value: "Part-time",
    code: "partTime",
  },
  {
    id: "PerDiem",
    category: "employee",
    name: "Per Diem",
    label: "Per Diem",
    value: "Per Diem",
    code: "perDiem",
  },
];
export const EMPLOYEE_POSITION = [
  {
    id: "caseManager",
    category: "position",
    name: "Case Manager",
    label: "Case Manager",
    value: "Case Manager",
    code: "CM",
    alias: "Nurse",
  },
  {
    id: "rn",
    category: "position",
    name: "Registered Nurse",
    label: "Registered Nurse",
    value: "Registered Nurse",
    code: "RN",
    alias: "Nurse",
  },
  {
    id: "don",
    category: "position",
    name: "Director of Nurse",
    label: "Director of Nurse",
    value: "Director of Nurse",
    code: "DON",
    alias: "DON",
  },
  {
    id: "cna",
    category: "position",
    name: "Certified Nurse Assistant",
    label: "Certified Nurse Assistant",
    value: "Certified Nurse Assistant",
    code: "CNA",
    alias: "CNA",
  },
  {
    id: "biller",
    category: "position",
    name: "Biller",
    label: "Biller",
    value: "Biller",
    code: "BILLER",
    alias: "Biller",
  },
  {
    id: "officeManager",
    category: "position",
    name: "Office Manager",
    label: "Office Manager",
    value: "Office Manager",
    code: "OM",
    alias: "Manager",
  },
  {
    id: "msw",
    category: "position",
    name: "MSW",
    label: "MSW",
    value: "MSW",
    code: "MS",
    alias: "MSW",
  },
  {
    id: "adminManager",
    category: "position",
    name: "Administrative Manager",
    label: "Administrative Manager",
    value: "Administrative Manager",
    code: "AM",
    alias: "Manager",
  },
  {
    id: "hr",
    category: "position",
    name: "Human Resources",
    label: "Human Resources",
    value: "Human Resources",
    code: "HR",
    alias: "HR",
  },
  {
    id: "officeStaff",
    category: "position",
    name: "Office Staff",
    label: "Office Staff",
    value: "Office Staff",
    code: "OS",
    alias: "Staff",
  },
  {
    id: "volunteer",
    category: "position",
    name: "Volunteer",
    label: "Volunteer",
    value: "Volunteer",
    code: "VR",
    alias: "Volunteer",
  },
  {
    id: "lpn",
    category: "position",
    name: "LPN",
    label: "LPN",
    value: "LPN",
    code: "LPN",
    alias: "LPN",
  },
  {
    id: "owner",
    category: "position",
    name: "Owner",
    label: "Owner",
    value: "Owner",
    code: "OR",
    alias: "Owner",
  },
  {
    id: "administrator",
    category: "position",
    name: "Administrator",
    label: "Administrator",
    value: "Administrator",
    code: "AR",
    alias: "Admin",
  },
  {
    id: "chaplain",
    category: "position",
    name: "Chaplain",
    label: "Chaplain",
    value: "Chaplain",
    code: "CH",
    alias: "Chaplain",
  },
  {
    id: "ceo",
    category: "position",
    name: "CEO",
    label: "CEO",
    value: "CEO",
    code: "CEO",
    alias: "CEO",
  },
  {
    id: "communityLiaison",
    category: "position",
    name: "Community Liaison",
    label: "Community Liaison",
    value: "Community Liaison",
    code: "CL",
    alias: "Liason",
  },
  {
    id: "medicalDirector",
    category: "position",
    name: "Medical Director",
    label: "Medical Director",
    value: "Medical Director",
    code: "MD",
    alias: "MD",
  },
  {
    id: "np",
    category: "position",
    name: "Nurse Practitioner",
    label: "Nurse Practitioner",
    value: "Nurse Practitioner",
    code: "NP",
    alias: "NP",
  },
];

export const EMPLOYEE_STATUS = [
  {
    id: "active",
    category: "status",
    name: "Active",
    label: "Active",
    value: "Active",
  },
  {
    id: "inactive",
    category: "status",
    name: "Inactive",
    label: "Inactive",
    value: "Inactive",
  },
];

export const STATUS_ACTIVE_OPTIONS = ["Active", "Inactive"];

export const CARE_TYPE = ["Assisted Living", "Home", "Group Home"];
export const EMPLOYMENT_STATUS = [
  "Full-Time",
  "Part-Time",
  "Per Diem",
  "End of Contract",
  "Termination",
  "Volunteer",
];

export const PATIENT_DASHBOARD_CATEGORY = [
  "Underpads",
  "Brief",
  "Underwear",
  "Wipe",
  "Glove",
  "Catheter",
  "Wound",
  "Other",
];

export const FULL_PATIENT_DASHBOARD_CATEGORY = [
  "Medical",
  "DME",
  "Transportation",
  "Pharmacy",
  "CNA",
  "Nurse",
  "MSW",
  "Chaplain",
  "LPN",
];
export const YEARS = [
  { name: "2022", value: "2022", label: "2022", id: "2022" },
  { name: "2023", value: "2023", label: "2023", id: "2023" },
];
export const YTD_LIST = [
  { from: "2023-04-01", to: "2023-04-30" },
  { from: "2023-05-01", to: "2023-05-30" },
  { from: "2023-06-01", to: "2023-06-30" },
];
export const DAY_OF_WEEK = [
  { name: "Mon", value: "Mon", label: "Mon", category: "day", id: "Mon" },
  { name: "Tue", value: "Tue", label: "Tue", category: "day", id: "Tue" },
  { name: "Wed", value: "Wed", label: "Wed", category: "day", id: "Wed" },
  { name: "Thu", value: "Thu", label: "Thu", category: "day", id: "Thu" },
  { name: "Fri", value: "Fri", label: "Fri", category: "day", id: "Fri" },
  { name: "Sat", value: "Sat", label: "Sat", category: "day", id: "Sat" },
  { name: "Sun", value: "Sun", label: "Sun", category: "day", id: "Sun" },
];
export const DME_EQUIPMENT = [
  {
    description: "Table",
    id: 1,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "Flat Mat",
    id: 2,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "",
    id: 3,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "",
    id: 4,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "",
    id: 5,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "",
    id: 6,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },
  {
    description: "",
    id: 7,
    tier1: false,
    tier2: false,
    tier3: false,
    tier1Rate: 3,
    tier2Rate: 4,
    tier3: 5,
    monthly: 10,
    perDiem: 5,
  },

  /*
  {
    name: "Bed",
    source: "main",
    description: "Bed",
    value: "Bed",
    label: "Bed",
    category: "equipment",
    id: "Bed",
  },
  {
    name: "Oxygen",
    description: "Oxygen",
    source: "main",
    value: "Oxygen",
    label: "Oxygen",
    category: "equipment",
    id: "Oxygen",
  },
  {
    name: "Chair",
    description: "Chair",
    source: "main",
    value: "Chair",
    label: "Chair",
    category: "Chair",
    id: "Oxygen",
  },
  */
];
export const SERVICE_TYPE = [
  {
    name: "Pickup",
    value: "Pickup",
    label: "Pickup",
    category: "service",
    id: "Pickup",
  },
  {
    name: "Delivery",
    value: "Delivery",
    label: "Delivery",
    category: "service",
    id: "Delivery",
  },
];
export const PATIENT_STATUS = [
  {
    name: "Active",
    value: "Active",
    label: "Active",
    category: "patientStatus",
  },
  {
    name: "InActive",
    value: "InActive",
    label: "InActive",
    category: "patientStatus",
  },
];
export const OFFICE_PARTICULAR = [
  "Regular Paper",
  "Carbonless Paper",
  "Binder",
  "Folder",
  "Brown Envelope",
  "Divider",
  "Labels",
  "Trash Bag",
  "Plastic Cup",
  "Utensils",
  "Paper Towel",
  "K-Cup Coffee",
];
export const UTILITIES_EXPENSE_BUDGET = [
  { name: "energy", label: "NV Energy", total: 0.0 },
  { name: "internetphone", label: "Cox Internet Phone", total: 0.0 },
  { name: "printer", label: "Printer Tangerine", total: 0.0 },
  { name: "water", label: "Refill Water", total: 0.0 },
  { name: "securecommunication", label: "QLIQ Soft", total: 0.0 },
];
export const OTHER_EXPENSE_BUDGET = [
  { name: "rent", label: "RENT", total: 0.0 },
  { name: "insurance", label: "INSURANCE", total: 0.0 },
  { name: "employee", label: "EMPLOYEE COST", total: 0.0 },
  { name: "dme", label: "DME", total: 0.0 },
  { name: "gmt", label: "GMT", total: 0.0 },
  { name: "pharmacy", label: "PHARMACY", total: 0.0 },
  { name: "foodentertainment", label: "FOOD/ENTERTAINMENT", total: 0.0 },
];
export const MONTH = [
  { id: 0, name: "Jan", value: "Jan", label: "Jan", category: "month" },
  { id: 1, name: "Feb", value: "Feb", label: "Feb", category: "month" },
  { id: 2, name: "Mar", value: "Mar", label: "Mar", category: "month" },
  { id: 3, name: "Apr", value: "Apr", label: "Apr", category: "month" },
  { id: 4, name: "May", value: "May", label: "May", category: "month" },
  { id: 5, name: "Jun", value: "Jun", label: "Jun", category: "month" },
  { id: 6, name: "Jul", value: "Jul", label: "Jul", category: "month" },
  { id: 7, name: "Aug", value: "Aug", label: "Aug", category: "month" },
  { id: 8, name: "Sep", value: "Sep", label: "Sep", category: "month" },
  { id: 9, name: "Oct", value: "Oct", label: "Oct", category: "month" },
  { id: 10, name: "Nov", value: "Nov", label: "Nov", category: "month" },
  { id: 11, name: "Dec", value: "Dec", label: "Dec", category: "month" },
];
export const YEAR = [
  { id: 0, name: "2023", value: "2023", label: "2023", category: "year" },
  { id: 1, name: "2024", value: "2024", label: "2024", category: "year" },
  { id: 2, name: "2025", value: "2025", label: "2025", category: "year" },
  { id: 3, name: "2026", value: "2026", label: "2026", category: "year" },
];
export const EMPLOYEE_PAYMENT_TYPE = [
  {
    id: 0,
    name: "Check",
    label: "Check",
    value: "check",
    category: "paymentType",
    code: "check",
  },
  {
    id: 1,
    name: "Cash",
    label: "Cash",
    value: "cash",
    category: "paymentType",
    code: "cash",
  },
  {
    id: 2,
    name: "Direct Deposit",
    label: "Direct Deposit",
    value: "direct deposit",
    category: "paymentType",
    code: "dp",
  },
];
export const PAY_PERIOD = [
  {
    payDate: "2023-12-31",
    payPeriod: "12/11/2023 - 12/24/2023",
  },
  {
    payDate: "2023-12-15",
    payPeriod: "11/26/2023 - 12/10/2023",
  },
  {
    payDate: "2023-11-30",
    payPeriod: "11/21/2023 - 11/25/2023",
  },
  {
    payDate: "2023-11-15",
    payPeriod: "10/27/2023 - 11/10/2023",
  },
  {
    payDate: "2023-10-15",
    payPeriod: "09/24/2023 - 10/07/2023",
  },
  {
    payDate: "2023-10-31",
    payPeriod: "10/08/2023 - 10/25/2023",
  },
  {
    payDate: "2024-01-15",
    payPeriod: "12/25/2023 - 01/10/2024",
  },
  {
    payDate: "2024-01-31",
    payPeriod: "01/11/2024 - 01/26/2024",
  },
  {
    payDate: "2024-02-15",
    payPeriod: "01/26/2024 - 02/10/2024",
  },
  {
    payDate: "2024-02-29",
    payPeriod: "02/11/2024 - 02/24/2024",
  },
  {
    payDate: "2024-03-15",
    payPeriod: "02/25/2024 - 03/10/2024",
  },
  {
    payDate: "2024-03-29",
    payPeriod: "03/11/2024 - 03/26/2024",
  },
  {
    payDate: "2024-04-15",
    payPeriod: "03/27/2024 - 04/10/2024",
  },
  {
    payDate: "2024-04-30",
    payPeriod: "04/11/2024 - 04/26/2024",
  },
  {
    payDate: "2024-05-15",
    payPeriod: "04/27/2024 - 05/10/2024",
  },
];
export const EMPLOYEE_SERVICE_TYPE = [
  {
    id: 1000,
    name: "Attendance",
    label: "Attendance",
    value: "Attendance",
    category: "serviceType",
    code: "ATD",
  },
  {
    id: 104,
    name: "Fixed Rate/Month",
    label: "Fixed Rate/Month",
    value: "Fixed Rate/Month",
    category: "serviceType",
    code: "FRM",
  },
  {
    id: 105,
    name: "Fixed Rate/Semi-Monthly",
    label: "Fixed Rate/Semi-Monthly",
    value: "Fixed Rate/Semi-Monthly",
    category: "serviceType",
    code: "FRSM",
  },
  {
    id: 0,
    name: "Full Time/Hr",
    label: "Full Time/Hr",
    value: "Full Time/Hr",
    category: "serviceType",
    code: "FT",
  },
  {
    id: 101,
    name: "Full Time/Salaried",
    label: "Full Time/Salaried",
    value: "Full Time/Salaried",
    category: "serviceType",
    code: "FT",
  },
  {
    id: 102,
    name: "Part Time/Hr",
    label: "Part Time/Hr",
    value: "Part Time/Hr",
    category: "serviceType",
    code: "PT",
  },
  {
    id: 1,
    name: "Evaluation Visit",
    label: "Evaluation Visit",
    value: "Evaluation Visit",
    category: "serviceType",
    code: "EV",
  },
  {
    id: 2,
    name: "Regular Visit",
    label: "Regular Visit",
    value: "Regular Visit",
    category: "serviceType",
    code: "RV",
  },
  {
    id: 21,
    name: "PRN",
    label: "PRN",
    value: "PRN",
    category: "serviceType",
    code: "PRN",
  },
  {
    id: 3,
    name: "Home Health Aid Visit",
    label: "Home Health Aid Visit",
    value: "Home Health Aid Visit",
    category: "serviceType",
    code: "HV",
  },
  {
    id: 4,
    name: "Orientation",
    label: "Orientation",
    value: "Orientation",
    category: "serviceType",
    code: "O",
  },
  {
    id: 5,
    name: "Chaplain Visit",
    label: "Chaplain Visit",
    value: "Chaplain Visit",
    category: "serviceType",
    code: "CV",
  },
  {
    id: 6,
    name: "Social Worker Visit",
    label: "Social Worker Visit",
    value: "Social Worker Visit",
    category: "serviceType",
    code: "SWV",
  },
  {
    id: 7,
    name: "Bereavement Visit",
    label: "Bereavement Visit",
    value: "Bereavement Visit",
    category: "serviceType",
    code: "BV",
  },
  {
    id: 8,
    name: "IDT Meeting in Person",
    label: "IDT Meeting in Person",
    value: "IDT Meeting in Person",
    category: "serviceType",
    code: "IDT",
  },
  {
    id: 9,
    name: "IDT Meeting via Phone",
    label: "IDT Meeting via Phone",
    value: "IDT Meeting via Phone",
    category: "serviceType",
    code: "IDT",
  },
  {
    id: 10,
    name: "IDT Meeting thru Notes",
    label: "IDT Meeting thru Notes",
    value: "IDT Meeting thru Notes",
    category: "serviceType",
    code: "IDT",
  },
  {
    id: 11,
    name: "Volunteer Visit",
    label: "Volunteer Visit",
    value: "Volunteer Visit",
    category: "serviceType",
    code: "VV",
  },
  {
    id: 12,
    name: "Employee Meeting",
    label: "Employee Meeting",
    value: "Employee Meeting",
    category: "serviceType",
    code: "EM",
  },
  {
    id: 13,
    name: "Inservice Meeting",
    label: "Inservice Meeting",
    value: "Inservice Meeting",
    category: "serviceType",
    code: "INS",
  },
  {
    id: 14,
    name: "On Call Visit",
    label: "On Call Visit",
    value: "On Call Visit",
    category: "serviceType",
    code: "OC",
  },
  {
    id: 141,
    name: "On Call/Day Phone",
    label: "On Call/Day Phone",
    value: "On Call/Day Phone",
    category: "serviceType",
    code: "OC",
  },
  {
    id: 142,
    name: "On Call/Hr Phone",
    label: "On Call/Hr Phone",
    value: "On Call/Hr Phone",
    category: "serviceType",
    code: "OC",
  },
  {
    id: 15,
    name: "Follow Up Visit",
    label: "Follow Up Visit",
    value: "Follow Up Visit",
    category: "serviceType",
    code: "F/UV",
  },
  {
    id: 16,
    name: "Supervisory Visit",
    label: "Supervisory Visit",
    value: "Supervisory Visit",
    category: "serviceType",
    code: "SV",
  },
  {
    id: 17,
    name: "Other",
    label: "Other",
    value: "Other",
    category: "serviceType",
    code: "Other",
  },
  {
    id: 17000,
    name: "Office Task",
    label: "Office Task",
    value: "Office Task",
    category: "serviceType",
    code: "Office Task",
  },
  {
    id: 18,
    name: "QA",
    label: "QA",
    value: "QA",
    category: "serviceType",
    code: "QA",
  },
  {
    id: 19,
    name: "Phone Call Visit",
    label: "Phone Call Visit",
    value: "Phone Call Visit",
    category: "serviceType",
    code: "PCV",
  },
  {
    id: 20,
    name: "Death Pronouncement",
    label: "Death Pronouncement",
    value: "Death Pronouncement",
    category: "serviceType",
    code: "DP",
  },
  {
    id: 21,
    name: "SOC/Assessment",
    label: "SOC/Assessment",
    value: "SOC/Assessment",
    category: "serviceType",
    code: "SOC",
  },
  {
    id: 21,
    name: "Reassessment",
    label: "Reassessment",
    value: "Reassessment",
    category: "serviceType",
    code: "REA",
  },
  {
    id: 80,
    name: "HUV",
    label: "HUV",
    value: "HUV",
    category: "serviceType",
    code: "HUV",
  },
  {
    id: 82,
    name: "SFV",
    label: "SFV",
    value: "SFV",
    category: "serviceType",
    code: "SFV",
  },
];

export const DME_SERVICE_TYPE = [
  {
    name: "Residence",
    value: "Residence",
    label: "Residence",
    description: "Residence",
    id: "Residence",
    category: "serviceType",
  },
  {
    name: "Group Home",
    value: "Group Home",
    label: "Group Home",
    description: "Group Home",
    id: "Group Home",
    category: "serviceType",
  },
  {
    name: "Facility",
    value: "Facility",
    label: "Facility",
    description: "Facility",
    id: "Facility",
    category: "serviceType",
  },
];
export const PRODUCT_CATEGORIES = [
  {
    name: "Adult Diapers and Briefs",
    value: "brief",
    label: "Adult Diapers and Briefs",
    category: "product",
    id: "Adult Diapers and Briefs",
  },
  {
    name: "Pull-up Underwear",
    value: "underwear",
    label: "Pull-up Underwear",
    category: "product",
    id: "Underwear",
  },
  {
    name: "Underpads",
    value: "underpad",
    label: "Underpads",
    category: "product",
    id: "Underpads",
  },
  {
    name: "Wipes",
    value: "wipe",
    label: "Wipes",
    category: "product",
    id: "Wipes",
  },
  {
    name: "Gloves",
    value: "glove",
    label: "Gloves",
    category: "product",
    id: "Gloves",
  },

  {
    name: "Ensure Vanilla",
    value: "ensureVanilla",
    label: "Ensure Vanilla",
    category: "product",
    id: "Ensure Vanilla",
  },
  {
    name: "Ensure Chocolate",
    value: "ensureChocolate",
    label: "Ensure Chocolate",
    category: "product",
    id: "Ensure Chocolate",
  },
  {
    name: "Ensure Strawberry",
    value: "ensureStrawberry",
    label: "Ensure Strawberry",
    category: "product",
    id: "Ensure Strawberry",
  },
];
export const INSURANCE = [
  {
    value: "Traditional Medicare",
    description: "Traditional Medicare",
    label: "Traditional Medicare",
    name: "Traditional Medicare",
    code: "TM",
    id: "TM",
    category: "insurance",
  },
  {
    value: "Medicare Advantage",
    description: "Medicare Advantage",
    label: "Medicare Advantage",
    name: "Medicare Advantage",
    code: "MA",
    id: "MA",
    category: "insurance",
  },
  {
    value: "Private Insurance",
    description: "Private Insurance",
    label: "Private Insurance",
    name: "Private Insurance",
    code: "PI",
    category: "insurance",
  },
  {
    value: "Medicaid",
    description: "Medicaid",
    label: "Medicaid",
    name: "Medicaid",
    code: "MD",
    category: "insurance",
  },
];

export const MEDICARE_CAP_AMOUNT = [
  { from: "2023-10-01", to: "2024-09-30", amount: 33494 },
  { from: "2024-10-01", to: "2025-09-30", amount: 34465.34 },
  { from: "2025-10-01", to: "2026-09-30", amount: 35361.44 },
];
export const DISCHARGE_REASON = [
  {
    name: "Death Discharge",
    value: "Death Discharge",
    label: "Death Discharge",
    description: "Death Discharge",
    category: "discharge",
    id: "Death Discharge",
  },

  {
    name: "Transfer another hospice",
    label: "Transfer another hospice",
    value: "Transfer another hospice",
    description: "Transfer another hospice",
    category: "discharge",
    id: "Transfer another hospice",
  },
  {
    name: "Travel outside of service area",
    value: "Travel outside of service area",
    label: "Travel outside of service area",
    description: "Travel outside of service area",
    category: "discharge",
    id: "Travel outside of service area",
  },
  {
    name: "Extended Prognosis",
    value: "Extended Prognosis",
    label: "Extended Prognosis",
    description: "Extended Prognosis",
    category: "discharge",
    id: "Extended Prognosis",
  },
  {
    name: "Discharge for cause",
    value: "Discharge for cause",
    label: "Discharge for cause",
    description: "Discharge for cause",
    category: "discharge",
    id: "Discharge for cause",
  },
  {
    name: "Revocation",
    value: "Revocation",
    label: "Revocation",
    description: "Revocation",
    category: "discharge",
    id: "Revocation",
  },
];

export const RATE_TYPE = [
  {
    name: "Salaried",
    label: "Salaried",
    value: "Salaried",
    description: "Salaried",
    category: "rateType",
    id: "Salaried",
  },
  {
    name: "Hourly",
    label: "Hourly",
    value: "Hourly",
    description: "Hourly",
    category: "rateType",
    id: "Hourly",
  },
  {
    name: "Per Visit",
    label: "Per Visit",
    value: "Per Visit",
    description: "Per Visit",
    category: "rateType",
    id: "Per Visit",
  },
  {
    name: "Fixed Rate",
    label: "Fixed Rate",
    value: "Fixed Rate",
    description: "Fixed Rate",
    category: "rateType",
    id: "Fixed Rate",
  },
];
export const VISIT_TYPE = [
  {
    id: "weekly",
    category: "visitType",
    name: "Weekly",
    label: "Weekly",
    value: "Week",
    code: "Week",
  },
  {
    id: "monthly",
    category: "visitType",
    name: "Monthly",
    label: "Monthly",
    value: "Month",
    code: "Month",
  },
];
export const IDT_POSITION = [
  {
    id: "rn",
    category: "position",
    name: "Registered Nurse",
    label: "Registered Nurse",
    value: "Registered Nurse",
    code: "RN",
    alias: "Nurse",
  },
  {
    id: "cna",
    category: "position",
    name: "Certified Nurse Assistant",
    label: "Certified Nurse Assistant",
    value: "Certified Nurse Assistant",
    code: "CNA",
    alias: "CNA",
  },
  {
    id: "msw",
    category: "position",
    name: "MSW",
    label: "MSW",
    value: "MSW",
    code: "MS",
    alias: "MSW",
  },
  {
    id: "volunteer",
    category: "position",
    name: "Volunteer",
    label: "Volunteer",
    value: "Volunteer",
    code: "VR",
    alias: "Volunteer",
  },
  {
    id: "lpn",
    category: "position",
    name: "LPN",
    label: "LPN",
    value: "LPN",
    code: "LPN",
    alias: "LPN",
  },
  {
    id: "chaplain",
    category: "position",
    name: "Chaplain",
    label: "Chaplain",
    value: "Chaplain",
    code: "CH",
    alias: "Chaplain",
  },
  {
    id: "bereavement",
    category: "position",
    name: "Bereavement",
    label: "Bereavement",
    value: "Bereavement",
    code: "CH",
    alias: "Bereavement",
  },
  {
    id: "medicalDirector",
    category: "position",
    name: "Medical Director",
    label: "Medical Director",
    value: "Medical Director",
    code: "MD",
    alias: "MD",
  },
  {
    id: "np",
    category: "position",
    name: "Nurse Practitioner",
    label: "Nurse Practitioner",
    value: "Nurse Practitioner",
    code: "NP",
    alias: "NP",
  },
];

export const US_STATES = [
  {
    id: "AL",
    name: "Alabama",
    label: "Alabama",
    value: "Alabama",
    category: "state",
    code: "AL",
  },
  {
    id: "AK",
    name: "Alaska",
    label: "Alaska",
    value: "Alaska",
    category: "state",
    code: "AK",
  },
  {
    id: "AZ",
    name: "Arizona",
    label: "Arizona",
    value: "Arizona",
    category: "state",
    code: "AZ",
  },
  {
    id: "AR",
    name: "Arkansas",
    label: "Arkansas",
    value: "Arkansas",
    category: "state",
    code: "AR",
  },
  {
    id: "CA",
    name: "California",
    label: "California",
    value: "California",
    category: "state",
    code: "CA",
  },
  {
    id: "CO",
    name: "Colorado",
    label: "Colorado",
    value: "Colorado",
    category: "state",
    code: "CO",
  },
  {
    id: "CT",
    name: "Connecticut",
    label: "Connecticut",
    value: "Connecticut",
    category: "state",
    code: "CT",
  },
  {
    id: "DE",
    name: "Delaware",
    label: "Delaware",
    value: "Delaware",
    category: "state",
    code: "DE",
  },
  {
    id: "FL",
    name: "Florida",
    label: "Florida",
    value: "Florida",
    category: "state",
    code: "FL",
  },
  {
    id: "GA",
    name: "Georgia",
    label: "Georgia",
    value: "Georgia",
    category: "state",
    code: "GA",
  },
  {
    id: "HI",
    name: "Hawaii",
    label: "Hawaii",
    value: "Hawaii",
    category: "state",
    code: "HI",
  },
  {
    id: "ID",
    name: "Idaho",
    label: "Idaho",
    value: "Idaho",
    category: "state",
    code: "ID",
  },
  {
    id: "IL",
    name: "Illinois",
    label: "Illinois",
    value: "Illinois",
    category: "state",
    code: "IL",
  },
  {
    id: "IN",
    name: "Indiana",
    label: "Indiana",
    value: "Indiana",
    category: "state",
    code: "IN",
  },
  {
    id: "IA",
    name: "Iowa",
    label: "Iowa",
    value: "Iowa",
    category: "state",
    code: "IA",
  },
  {
    id: "KS",
    name: "Kansas",
    label: "Kansas",
    value: "Kansas",
    category: "state",
    code: "KS",
  },
  {
    id: "KY",
    name: "Kentucky",
    label: "Kentucky",
    value: "Kentucky",
    category: "state",
    code: "KY",
  },
  {
    id: "LA",
    name: "Louisiana",
    label: "Louisiana",
    value: "Louisiana",
    category: "state",
    code: "LA",
  },
  {
    id: "ME",
    name: "Maine",
    label: "Maine",
    value: "Maine",
    category: "state",
    code: "ME",
  },
  {
    id: "MD",
    name: "Maryland",
    label: "Maryland",
    value: "Maryland",
    category: "state",
    code: "MD",
  },
  {
    id: "MA",
    name: "Massachusetts",
    label: "Massachusetts",
    value: "Massachusetts",
    category: "state",
    code: "MA",
  },
  {
    id: "MI",
    name: "Michigan",
    label: "Michigan",
    value: "Michigan",
    category: "state",
    code: "MI",
  },
  {
    id: "MN",
    name: "Minnesota",
    label: "Minnesota",
    value: "Minnesota",
    category: "state",
    code: "MN",
  },
  {
    id: "MS",
    name: "Mississippi",
    label: "Mississippi",
    value: "Mississippi",
    category: "state",
    code: "MS",
  },
  {
    id: "MO",
    name: "Missouri",
    label: "Missouri",
    value: "Missouri",
    category: "state",
    code: "MO",
  },
  {
    id: "MT",
    name: "Montana",
    label: "Montana",
    value: "Montana",
    category: "state",
    code: "MT",
  },
  {
    id: "NE",
    name: "Nebraska",
    label: "Nebraska",
    value: "Nebraska",
    category: "state",
    code: "NE",
  },
  {
    id: "NV",
    name: "Nevada",
    label: "Nevada",
    value: "Nevada",
    category: "state",
    code: "NV",
  },
  {
    id: "NH",
    name: "New Hampshire",
    label: "New Hampshire",
    value: "New Hampshire",
    category: "state",
    code: "NH",
  },
  {
    id: "NJ",
    name: "New Jersey",
    label: "New Jersey",
    value: "New Jersey",
    category: "state",
    code: "NJ",
  },
  {
    id: "NM",
    name: "New Mexico",
    label: "New Mexico",
    value: "New Mexico",
    category: "state",
    code: "NM",
  },
  {
    id: "NY",
    name: "New York",
    label: "New York",
    value: "New York",
    category: "state",
    code: "NY",
  },
  {
    id: "NC",
    name: "North Carolina",
    label: "North Carolina",
    value: "North Carolina",
    category: "state",
    code: "NC",
  },
  {
    id: "ND",
    name: "North Dakota",
    label: "North Dakota",
    value: "North Dakota",
    category: "state",
    code: "ND",
  },
  {
    id: "OH",
    name: "Ohio",
    label: "Ohio",
    value: "Ohio",
    category: "state",
    code: "OH",
  },
  {
    id: "OK",
    name: "Oklahoma",
    label: "Oklahoma",
    value: "Oklahoma",
    category: "state",
    code: "OK",
  },
  {
    id: "OR",
    name: "Oregon",
    label: "Oregon",
    value: "Oregon",
    category: "state",
    code: "OR",
  },
  {
    id: "PA",
    name: "Pennsylvania",
    label: "Pennsylvania",
    value: "Pennsylvania",
    category: "state",
    code: "PA",
  },
  {
    id: "RI",
    name: "Rhode Island",
    label: "Rhode Island",
    value: "Rhode Island",
    category: "state",
    code: "RI",
  },
  {
    id: "SC",
    name: "South Carolina",
    label: "South Carolina",
    value: "South Carolina",
    category: "state",
    code: "SC",
  },
  {
    id: "SD",
    name: "South Dakota",
    label: "South Dakota",
    value: "South Dakota",
    category: "state",
    code: "SD",
  },
  {
    id: "TN",
    name: "Tennessee",
    label: "Tennessee",
    value: "Tennessee",
    category: "state",
    code: "TN",
  },
  {
    id: "TX",
    name: "Texas",
    label: "Texas",
    value: "Texas",
    category: "state",
    code: "TX",
  },
  {
    id: "UT",
    name: "Utah",
    label: "Utah",
    value: "Utah",
    category: "state",
    code: "UT",
  },
  {
    id: "VT",
    name: "Vermont",
    label: "Vermont",
    value: "Vermont",
    category: "state",
    code: "VT",
  },
  {
    id: "VA",
    name: "Virginia",
    label: "Virginia",
    value: "Virginia",
    category: "state",
    code: "VA",
  },
  {
    id: "WA",
    name: "Washington",
    label: "Washington",
    value: "Washington",
    category: "state",
    code: "WA",
  },
  {
    id: "WV",
    name: "West Virginia",
    label: "West Virginia",
    value: "West Virginia",
    category: "state",
    code: "WV",
  },
  {
    id: "WI",
    name: "Wisconsin",
    label: "Wisconsin",
    value: "Wisconsin",
    category: "state",
    code: "WI",
  },
  {
    id: "WY",
    name: "Wyoming",
    label: "Wyoming",
    value: "Wyoming",
    category: "state",
    code: "WY",
  },
];
