// US Counties by State
export const US_COUNTIES = {
  Nevada: [
    { id: "clark", name: "Clark", label: "Clark", value: "Clark", category: "county" },
    { id: "washoe", name: "Washoe", label: "Washoe", value: "Washoe", category: "county" },
    { id: "carson-city", name: "Carson City", label: "Carson City", value: "Carson City", category: "county" },
    { id: "churchill", name: "Churchill", label: "Churchill", value: "Churchill", category: "county" },
    { id: "douglas", name: "Douglas", label: "Douglas", value: "Douglas", category: "county" },
    { id: "elko", name: "Elko", label: "Elko", value: "Elko", category: "county" },
    { id: "esmeralda", name: "Esmeralda", label: "Esmeralda", value: "Esmeralda", category: "county" },
    { id: "eureka", name: "Eureka", label: "Eureka", value: "Eureka", category: "county" },
    { id: "humboldt", name: "Humboldt", label: "Humboldt", value: "Humboldt", category: "county" },
    { id: "lander", name: "Lander", label: "Lander", value: "Lander", category: "county" },
    { id: "lincoln", name: "Lincoln", label: "Lincoln", value: "Lincoln", category: "county" },
    { id: "lyon", name: "Lyon", label: "Lyon", value: "Lyon", category: "county" },
    { id: "mineral", name: "Mineral", label: "Mineral", value: "Mineral", category: "county" },
    { id: "nye", name: "Nye", label: "Nye", value: "Nye", category: "county" },
    { id: "pershing", name: "Pershing", label: "Pershing", value: "Pershing", category: "county" },
    { id: "storey", name: "Storey", label: "Storey", value: "Storey", category: "county" },
    { id: "white-pine", name: "White Pine", label: "White Pine", value: "White Pine", category: "county" },
  ],
  California: [
    { id: "los-angeles", name: "Los Angeles", label: "Los Angeles", value: "Los Angeles", category: "county" },
    { id: "san-diego", name: "San Diego", label: "San Diego", value: "San Diego", category: "county" },
    { id: "orange", name: "Orange", label: "Orange", value: "Orange", category: "county" },
    { id: "riverside", name: "Riverside", label: "Riverside", value: "Riverside", category: "county" },
    { id: "san-bernardino", name: "San Bernardino", label: "San Bernardino", value: "San Bernardino", category: "county" },
    { id: "santa-clara", name: "Santa Clara", label: "Santa Clara", value: "Santa Clara", category: "county" },
    { id: "alameda", name: "Alameda", label: "Alameda", value: "Alameda", category: "county" },
    { id: "sacramento", name: "Sacramento", label: "Sacramento", value: "Sacramento", category: "county" },
    { id: "contra-costa", name: "Contra Costa", label: "Contra Costa", value: "Contra Costa", category: "county" },
    { id: "fresno", name: "Fresno", label: "Fresno", value: "Fresno", category: "county" },
    { id: "kern", name: "Kern", label: "Kern", value: "Kern", category: "county" },
    { id: "san-francisco", name: "San Francisco", label: "San Francisco", value: "San Francisco", category: "county" },
    { id: "ventura", name: "Ventura", label: "Ventura", value: "Ventura", category: "county" },
    { id: "san-mateo", name: "San Mateo", label: "San Mateo", value: "San Mateo", category: "county" },
    { id: "san-joaquin", name: "San Joaquin", label: "San Joaquin", value: "San Joaquin", category: "county" },
    { id: "stanislaus", name: "Stanislaus", label: "Stanislaus", value: "Stanislaus", category: "county" },
    { id: "sonoma", name: "Sonoma", label: "Sonoma", value: "Sonoma", category: "county" },
    { id: "tulare", name: "Tulare", label: "Tulare", value: "Tulare", category: "county" },
    { id: "santa-barbara", name: "Santa Barbara", label: "Santa Barbara", value: "Santa Barbara", category: "county" },
    { id: "monterey", name: "Monterey", label: "Monterey", value: "Monterey", category: "county" },
  ],
  Arizona: [
    { id: "maricopa", name: "Maricopa", label: "Maricopa", value: "Maricopa", category: "county" },
    { id: "pima", name: "Pima", label: "Pima", value: "Pima", category: "county" },
    { id: "pinal", name: "Pinal", label: "Pinal", value: "Pinal", category: "county" },
    { id: "yuma", name: "Yuma", label: "Yuma", value: "Yuma", category: "county" },
    { id: "mohave", name: "Mohave", label: "Mohave", value: "Mohave", category: "county" },
    { id: "coconino", name: "Coconino", label: "Coconino", value: "Coconino", category: "county" },
    { id: "apache", name: "Apache", label: "Apache", value: "Apache", category: "county" },
    { id: "navajo", name: "Navajo", label: "Navajo", value: "Navajo", category: "county" },
    { id: "cochise", name: "Cochise", label: "Cochise", value: "Cochise", category: "county" },
    { id: "yavapai", name: "Yavapai", label: "Yavapai", value: "Yavapai", category: "county" },
    { id: "gila", name: "Gila", label: "Gila", value: "Gila", category: "county" },
    { id: "graham", name: "Graham", label: "Graham", value: "Graham", category: "county" },
    { id: "la-paz", name: "La Paz", label: "La Paz", value: "La Paz", category: "county" },
    { id: "santa-cruz", name: "Santa Cruz", label: "Santa Cruz", value: "Santa Cruz", category: "county" },
    { id: "greenlee", name: "Greenlee", label: "Greenlee", value: "Greenlee", category: "county" },
  ],
  // Add more states as needed - providing a subset for now
  Texas: [
    { id: "harris", name: "Harris", label: "Harris", value: "Harris", category: "county" },
    { id: "dallas", name: "Dallas", label: "Dallas", value: "Dallas", category: "county" },
    { id: "tarrant", name: "Tarrant", label: "Tarrant", value: "Tarrant", category: "county" },
    { id: "bexar", name: "Bexar", label: "Bexar", value: "Bexar", category: "county" },
    { id: "travis", name: "Travis", label: "Travis", value: "Travis", category: "county" },
    { id: "collin", name: "Collin", label: "Collin", value: "Collin", category: "county" },
    { id: "el-paso", name: "El Paso", label: "El Paso", value: "El Paso", category: "county" },
    { id: "denton", name: "Denton", label: "Denton", value: "Denton", category: "county" },
    { id: "fort-bend", name: "Fort Bend", label: "Fort Bend", value: "Fort Bend", category: "county" },
    { id: "hidalgo", name: "Hidalgo", label: "Hidalgo", value: "Hidalgo", category: "county" },
  ],
  Florida: [
    { id: "miami-dade", name: "Miami-Dade", label: "Miami-Dade", value: "Miami-Dade", category: "county" },
    { id: "broward", name: "Broward", label: "Broward", value: "Broward", category: "county" },
    { id: "palm-beach", name: "Palm Beach", label: "Palm Beach", value: "Palm Beach", category: "county" },
    { id: "hillsborough", name: "Hillsborough", label: "Hillsborough", value: "Hillsborough", category: "county" },
    { id: "orange", name: "Orange", label: "Orange", value: "Orange", category: "county" },
    { id: "pinellas", name: "Pinellas", label: "Pinellas", value: "Pinellas", category: "county" },
    { id: "duval", name: "Duval", label: "Duval", value: "Duval", category: "county" },
    { id: "lee", name: "Lee", label: "Lee", value: "Lee", category: "county" },
    { id: "polk", name: "Polk", label: "Polk", value: "Polk", category: "county" },
    { id: "brevard", name: "Brevard", label: "Brevard", value: "Brevard", category: "county" },
  ],
  // Placeholder for other states - returns empty array if state not defined
};

export const getCountiesByState = (stateName) => {
  return US_COUNTIES[stateName] || [];
};
